### ISSUE TITLE
[Android] Expose a Composable rich text editor

### ISSUE THREAD

**Issue by bmarty** [matrix-org/matrix-rich-text-editor#315]
To integrate the editor to an Android application written using Jetpack Compose, the Android library should expose a Composable editor, i.e. a method annotated with `@Composable`.

Will be useful for https://github.com/vector-im/element-x-android-poc/issues/1, however this is not blocking us.

### Tasks
- [x] https://github.com/matrix-org/matrix-rich-text-editor/pull/754
  - [x] Theming and dark mode
- [x] https://github.com/matrix-org/matrix-rich-text-editor/pull/755
- [x] https://github.com/matrix-org/matrix-rich-text-editor/pull/758
- [x] https://github.com/matrix-org/matrix-rich-text-editor/pull/760
  - [x] Add usage documentation
- [x] Fix: https://github.com/matrix-org/matrix-rich-text-editor/pull/764
- [x] https://github.com/matrix-org/matrix-rich-text-editor/pull/766
  - [x] Focus API
  - [x] Line count API
  - [x] Text and cursor style settings
- [x] https://github.com/matrix-org/matrix-rich-text-editor/pull/767
- [x] Release

### Out of scope
- Feature parity with View library
